// Datos de ubicación para Venezuela
export const estados = [
  { id: 1, nombre: "Amazonas" },
  { id: 2, nombre: "Anzoátegui" },
  { id: 3, nombre: "Apure" },
  { id: 4, nombre: "Aragua" },
  { id: 5, nombre: "Barinas" },
  { id: 6, nombre: "Bolívar" },
  { id: 7, nombre: "Carabobo" },
  { id: 8, nombre: "Cojedes" },
  { id: 9, nombre: "Delta Amacuro" },
  { id: 10, nombre: "Distrito Capital" },
  { id: 11, nombre: "Falcón" },
  { id: 12, nombre: "Guárico" },
  { id: 13, nombre: "Lara" },
  { id: 14, nombre: "Mérida" },
  { id: 15, nombre: "Miranda" },
  { id: 16, nombre: "Monagas" },
  { id: 17, nombre: "Nueva Esparta" },
  { id: 18, nombre: "Portuguesa" },
  { id: 19, nombre: "Sucre" },
  { id: 20, nombre: "Táchira" },
  { id: 21, nombre: "Trujillo" },
  { id: 22, nombre: "Vargas" },
  { id: 23, nombre: "Yaracuy" },
  { id: 24, nombre: "Zulia" },
]

// Ciudades por estado (muestra para algunos estados)
export const ciudades = {
  1: [
    { id: 1, nombre: "Puerto Ayacucho" },
    { id: 2, nombre: "San Fernando de Atabapo" },
    { id: 3, nombre: "Maroa" },
  ],
  2: [
    { id: 4, nombre: "Barcelona" },
    { id: 5, nombre: "Puerto La Cruz" },
    { id: 6, nombre: "El Tigre" },
    { id: 7, nombre: "Anaco" },
  ],
  10: [{ id: 8, nombre: "Caracas" }],
  15: [
    { id: 9, nombre: "Los Teques" },
    { id: 10, nombre: "Guarenas" },
    { id: 11, nombre: "Guatire" },
    { id: 12, nombre: "Petare" },
  ],
  24: [
    { id: 13, nombre: "Maracaibo" },
    { id: 14, nombre: "Cabimas" },
    { id: 15, nombre: "Ciudad Ojeda" },
    { id: 16, nombre: "San Francisco" },
  ],
}

// Municipios por ciudad (muestra para algunas ciudades)
export const municipios = {
  8: [
    { id: 1, nombre: "Libertador" },
    { id: 2, nombre: "Chacao" },
    { id: 3, nombre: "Baruta" },
    { id: 4, nombre: "Sucre" },
    { id: 5, nombre: "El Hatillo" },
  ],
  13: [
    { id: 6, nombre: "Maracaibo" },
    { id: 7, nombre: "San Francisco" },
    { id: 8, nombre: "Jesús Enrique Lossada" },
    { id: 9, nombre: "La Cañada de Urdaneta" },
  ],
  4: [
    { id: 10, nombre: "Simón Bolívar" },
    { id: 11, nombre: "Sotillo" },
    { id: 12, nombre: "Guanta" },
  ],
}

// Datos de pacientes para la base de datos
export const pacientesData = [
  {
    id: 1,
    nombre: "Juan",
    apellido: "Pérez",
    genero: "masculino",
    tipo_cedula: "V",
    cedula: "12345678",
    fecha_nacimiento: "1985-05-15",
    estado: "Distrito Capital",
    ciudad: "Caracas",
    municipio: "Libertador",
    direccion: "Av. Universidad, Edificio Central, Apto 5-B",
    email: "juan.perez@example.com",
    telefono: "0414-1234567",
  },
  {
    id: 2,
    nombre: "María",
    apellido: "González",
    genero: "femenino",
    tipo_cedula: "V",
    cedula: "23456789",
    fecha_nacimiento: "1990-08-22",
    estado: "Miranda",
    ciudad: "Los Teques",
    municipio: "Guaicaipuro",
    direccion: "Calle Rivas, Casa 45",
    email: "maria.gonzalez@example.com",
    telefono: "0424-9876543",
  },
  {
    id: 3,
    nombre: "Carlos",
    apellido: "Rodríguez",
    genero: "masculino",
    tipo_cedula: "E",
    cedula: "84567123",
    fecha_nacimiento: "1978-11-30",
    estado: "Zulia",
    ciudad: "Maracaibo",
    municipio: "Maracaibo",
    direccion: "Av. 5 de Julio, Residencias El Lago, Piso 8, Apto 8-C",
    email: "carlos.rodriguez@example.com",
    telefono: "0416-5551234",
  },
  {
    id: 4,
    nombre: "Ana",
    apellido: "Martínez",
    genero: "femenino",
    tipo_cedula: "V",
    cedula: "19876543",
    fecha_nacimiento: "1995-03-10",
    estado: "Carabobo",
    ciudad: "Valencia",
    municipio: "Valencia",
    direccion: "Urbanización El Trigal, Calle 5, Casa 12",
    email: "ana.martinez@example.com",
    telefono: "0412-3334444",
  },
  {
    id: 5,
    nombre: "Pedro",
    apellido: "López",
    genero: "masculino",
    tipo_cedula: "E",
    cedula: "12345987",
    fecha_nacimiento: "1982-07-18",
    estado: "Aragua",
    ciudad: "Maracay",
    municipio: "Girardot",
    direccion: "Av. Bolívar, Centro Comercial Las Américas, Local 25",
    email: "pedro.lopez@example.com",
    telefono: "0426-7778888",
  },
]

// Datos de consultas odontológicas
export const consultasData = [
  {
    id: 1,
    paciente_id: 1,
    fecha: "2023-04-07",
    motivo: "Revisión general",
    odontologo: "Dr. García",
  },
  {
    id: 2,
    paciente_id: 2,
    fecha: "2023-04-06",
    motivo: "Dolor molar",
    odontologo: "Dra. Rodríguez",
  },
  {
    id: 3,
    paciente_id: 3,
    fecha: "2023-04-05",
    motivo: "Limpieza dental",
    odontologo: "Dr. García",
  },
  {
    id: 4,
    paciente_id: 4,
    fecha: "2023-04-04",
    motivo: "Extracción",
    odontologo: "Dra. Rodríguez",
  },
  {
    id: 5,
    paciente_id: 5,
    fecha: "2023-04-03",
    motivo: "Ortodoncia",
    odontologo: "Dr. García",
  },
]
